# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yassine Kessal
email: yassine.ronni.kessal@outlook.com
display_name: Yassine Kessal

profile_picture: https://scontent-mrs1-1.xx.fbcdn.net/v/t1.0-9/15822651_1241951439184025_3125284242249075910_n.jpg?oh=e0bc932fcff4f60ee2349a8e82a88854&oe=59E6F5D4

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yassine-kessal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_url: https://twitter.com/yassine_kessal
github_url: https://github.com/yassine-kessal
facebook_url: https://www.facebook.com/ykessal
linkedin_url: https://www.linkedin.com/in/yassine-kessal-a70239113/

paginate: 6
paginate_path: "/journal/page:num"

permalink: /journal/:title

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
